### ISSUE TITLE
Serialization error after upgrade to v5.0.0

### ISSUE THREAD

**Issue by LodewijkSioen** [khellang/Middleware#102]
So I have this code in my Startup.cs:
```
services.AddProblemDetails(setup =>
 {
    setup.IncludeExceptionDetails = (c, e) => environment.IsDevelopment(); // -> before updating to v5, I had _ =>environment.IsDevelopment(); here
    setup.Map<DomainValidationException>(
        (context, ex) => new ValidationProblemDetails(ex.Errors).Build(context));
});
```
Now my json looks like this, which blows up in deserialisation because of the duplicate "errors" field:
```
  {
    "errors": {
        "exportPath": [
            "..."
        ]
    },
    "type": "https://httpstatuses.com/400",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "detail": "Please refer to the errors property for additional details.",
    "instance": "/api/externalApplications/4240656a-a669-4fba-842a-abbb00dca30f",
    "errors": [
        {
            "message": "Domain validation failed. See Errors for details.",
[...]
```
Before the update (v4.5), the json was just
```
{
    "errors": {
        "exportPath": [
            "..."
        ]
    },
    "type": "https://httpstatuses.com/400",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "detail": "Please refer to the errors property for additional details.",
    "instance": "/api/externalApplications/7a52e19a-ce16-480c-9999-abbb00e0c8c7"
}
```

Fixed it by doing this in my startup, but I don't know if this is what you intended:
```
setup.IncludeExceptionDetails = (c, e) =>
{
     return e switch
     {
         DomainValidationException _ => false,
         _ => environment.IsDevelopment()
    };
};
```

**Comment by khellang** [comment]
Ouch, yeah, that is absolutely not what I intended 😅

I did actually think about this scenario, given `errors` is a fairly generic property name, but couldn't figure out a good way to solve it (at the time) and ended up forgetting about it 😂 

FWIW, I think this could be a serializer bug as well. In 5.0, I rely on `JsonExtensionData` to augment problem details by adding exception details. I would've expected that the existing `errors` property was overwritten instead of appending an additional property with the same name.

I guess the simplest solution would be to just make the property name configurable. Trying to figure out whether a property with that name already exists would probably reqiure reflection and JSON naming policies, which seems overkill. And if the property exist, what do you do? Go through a list of alternatives?

**Comment by khellang** [comment]
> FWIW, I think this could be a serializer bug as well.

Scratch that, it seems this is totally intended. There's even [a test for it](https://github.com/dotnet/runtime/blob/230538bb8d1a6a7039c1873fc1e69fd5bb54b024/src/libraries/System.Text.Json/tests/Serialization/ExtensionDataTests.cs#L491-L509) 😰

**Comment by khellang** [comment]
Just pushed v5.1.0 to NuGet. It has an additional `ExceptionDetailsPropertyName` option that should let you use a different name 😄

**Comment by LodewijkSioen** [comment]
Excellent! Thank you very much!

**Comment by shatl** [comment]
exceptionDetails maybe ?

**Comment by angularsen** [comment]
@khellang I was just hit by this too, 1 year later on 5.4 after upgrading from 4.5. 
I second the ☝️ suggestion of changing the default name to `exceptionDetails`.

Out of the box, we run into problems with Refit no longer recognizing the validation error and throws `Refit.ApiException` instead of `Refit.ApiValidationException`, which loses the `ProblemDetails` it tries to deserialize for 400 Bad Request. Changing the property name fixed this.
