### ISSUE TITLE
Target netstandard instead of netcoreapp

### ISSUE THREAD

**Issue by tioduke** [khellang/Middleware#103]
Hi,

I've been using ProblemDetails from some time now. For the time being, I had to stick to an older version because my library is compiled against nestandard2.0.

I understand that ProblemDeatils is meant to be used in Top Level projects (weapps), however bringing back netstandard as a dependency instead of netcoreapp could be great for cases like mine where the common face lifting is done in libraries instead of every single application.

If you are unable to target nestandard2.0 beacuse of dependencies of your own, would you consider targetting netsandard2.1? : I can live with one of my libraries targetting a more recent version (as, in my case, the compatibility towards nestandard2.0 is needed mainly for BLL libraries).

Thank you in advance.

**Comment by khellang** [comment]
Hi @tioduke!

> For the time being, I had to stick to an older version because my library is compiled against nestandard2.0.

Just because it has a lower version number, doesn't mean it's old. Several features were backported to the 4.x branch (which I will keep maintaining for some time) and released at the same time as 5.0, which is the version I switched to netcoreapp. It should be no problem to keep using the 4.x release train. The reason I switched to netcoreapp because I rely on newer APIs in ASP.NET Core 3.x, which itself doesn't target netstandard.

> If you are unable to target nestandard2.0 beacuse of dependencies of your own, would you consider targetting netsandard2.1?

Because of what I mentioned above, there's basically no way to target anything else. Not even netstandard2.1.

Is there a particular reason why you have to target netstandard2.0? All libraries for web apps will have to move to netcoreapp (or just net5.0) when taking dependencies on newer APIs soon anyway.

**Comment by tioduke** [comment]
I didn't know realize about the 4.x version still being maintained. I will stick with it for the time being.

As of why I am targetting netstandard. The company I work for is a full-blown dotnet full framework shop and the project I am working now is the first to use dotnet core. Upper management is kinda nervous of any type of change and are demanding to have a plan B in case we hit a major obstacle. That's why I am targetting netstandard 2.0 for libraries, so that I could easily use those libraries in dotnet full rfameowrk without worries. This is more for BLL than "infrastructure" libraries.

I am however confident that their fears will disappear in the near future but for that I need to be able to deliver in production. Now with this pandemic many things have paused, including my projet, so I have to wait a little for now.

Anyway, thank you for taking your time to explain this to me. And thank you for making ProblemDetails.
