### ISSUE TITLE
Configurable behaviour for Cache-Control, Expires, Pragma headers

### ISSUE THREAD

**Issue by gw79** [khellang/Middleware#108]
Please consider adding support for overriding the default behaviour of adding Cache-Control, Expires and Pragma headers.

This could easily be done via a Action&lt;IHeaderDictionary&gt; property on ProblemDetailsOptions, similar to other extensibility points.

My motivation for this request is admittedly needing to adhere to my own company's HTTP header standards and having to add a OnBeforeWriteDetails workaround to suit them, but also:

1. Pragma is deprecated, usage of it should not be hard-coded.
2. Expires is unnecessary with Cache-Control: no-store, which implies max-age=0

Happy to submit a PR for this if you're willing to accept, thanks.

**Comment by khellang** [comment]
Hello @gw79! 👋

Thanks for filing this issue. Those headers were all added for a reason 😉 The caching headers is based off [the ASP.NET Core exception handler middleware](https://github.com/dotnet/aspnetcore/blob/36f6242e6f84208bc1c9d2c4cac94cbb134196df/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L176-L178) and [this StackOverflow answer](https://stackoverflow.com/q/49547). It's basically trying to be as compatible as possible.

Before adding yet another knob to the options API, I would like to know a bit more about why one would care about these headers. Is is because of the byte count on the wire? Security?

Especially since there are existing workarounds (either using an existing ProblemDetails hook or having a custom MW that strips these headers, which would cover other components using them as well) and this is the first time anyone's cared about it 😅

**Comment by khellang** [comment]
Hi @gw79! 👋🏻 

I just pushed a new version, v5.2.0, to NuGet with this feature if you're interested in testing it out 😄 

It can be configured like this:

```csharp
services.AddProblemDetails(x =>
{
    x.AppendCacheHeaders = (ctx, headers) =>
    {
        // TODO: Append headers here...
    };
});
```

**Comment by gw79** [comment]
Ah, thanks Kristian, I'll give it a look tomorrow.  

To try to answer your question about why one would care about the headers...  I personally don't all that much!
We have some fairly strict and sometimes erroneous and puzzling standards for API behaviour set by our architecture team.
Mostly designed in order to achieve consistency for APIs developed by different teams/departments, but I guess also with simplicity and security in mind.

For these caching headers you could indeed argue it's more secure to have all bases covered, but if you know the consumer of your API is always another API rather than a web browser, it's overkill.
