### ISSUE TITLE
[ProblemDetails] Feature request: Add attribute-based way of returning ValidationProblemDetails

### ISSUE THREAD

**Issue by IanKemp** [khellang/Middleware#112]
The current ProblemDetails package API allows you to throw validation exceptions that are then transformed into `ValidationProblemDetails` instances. However, using exceptions for control flow is considered bad practice. The current implementation also requires a custom exception class to be created, that is then mapped back to the required `ValidationProblemDetails` subclass. It would be useful if there was an alternate way to express that validation issues should be returned as `ValidationProblemDetails` to the client.

In fact, there is a way this is already (kind of) achieved: using the `System.ComponentModel.DataAnnotations.ValidationAttribute` class. A member decorated with this attribute will be validated, and if it fails validation, will return a message, which can optionally include the names of the affected members. ASP.NET Core, in fact, already supports this attribute out of the box: using it will yield, in the case of failed validation details, a `ValidationProblemDetails` that has its `Errors` dictionary populated with the message (and affected member names, if provided).

However, this is too rigid for some situations, in that it doesn't allow you to return multiple elements in `ValidationProblemDetails.Errors`. It's also the case that you might wish to enrich/mutate other properties of `ValidationProblemDetails`, which you simply cannot do with `ValidationAttribute`. Hence I propose the following:

* A new `ValidationProblemDetailsValidationAttribute` class defined as such:

```cs
public abstract class ValidationProblemDetailsValidationAttribute : Attribute
{
    // subclasses must override this to do their validation, and return a ValidationProblemDetails if validation fails
    public virtual async Task<ValidationProblemDetails> ValidateAsync(object value)
        => default;
}
```

and appropriate model binder that searches for attributes deriving from the above class applied wherever the user chooses. When it finds such an attribute, it creates an instance, passes in the appropriate object to the subclass's `ValidateAsync`, and if that returns non-null, immediately stops and returns the `ValidationProblemDetails` in the standard manner.

**Essentially, it's `ValidationAttribute`, but returning `ValidationProblemDetails` instead of just an error message.**

**Comment by khellang** [comment]
Hi @IanKemp! Thanks for the feature request 😄 

> The current implementation also requires a custom exception class to be created, that is then mapped back to the required `ValidationProblemDetails` subclass.

Using `ValidationProblemDetails` is not required, it's simply just convenient to use because the type comes with the framework. You don't really have to create your own exception type either. Most libraries/frameworks already have their own exception type for validation results (see below.)

> It would be useful if there was an alternate way to express that validation issues should be returned as `ValidationProblemDetails` to the client.

You can always do this in your application layer, which is what I would recommend. The middleware uses the MVC formatter pipeline to transform the result into JSON, so they should produce the exact same result. See the sample:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/samples/ProblemDetails.Sample/Program.cs#L137-L147

> However, using exceptions for control flow is considered bad practice.

I kinda agree, but at the same time, most (if not all?) validation libraries (can) throw exceptions on failed validation. I.e. `System.ComponentModel.DataAnnotations`, which you referred to, already has [`ValidationException`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validationexception?view=net-5.0):

> This class uses the `ValidationAttribute` class to customize validations. A `ValidationException` is thrown if a validation error occurs. The exception is thrown when the 
`Validate` method is called. 

Other libraries, like FluentValidation, which I use almost exclusively, also have [the same concepts](https://docs.fluentvalidation.net/en/latest/start.html#throwing-exceptions).

> However, this is too rigid for some situations, in that it doesn't allow you to return multiple elements in `ValidationProblemDetails.Errors`. 

Can't you just add to the `ModelState` dictionary in MVC?

> **Essentially, it's `ValidationAttribute`, but returning `ValidationProblemDetails` instead of just an error message.**

What I'm getting to is I don't think this library should start getting into validation territory. I think the right place for this is in your application code, not in a generic error handling middleware 😄
