### ISSUE TITLE
No way to handle exception with other error handlers after ProblemDetailsMiddleware

### ISSUE THREAD

**Issue by vovapabyr** [khellang/Middleware#114]
Hi @khellang 

I have a hybrid application that combines razor pages and web API. When some exception happens on razor pages I need to display a user-friendly error page, which I used to do with ExceptionHandlerMiddleware `app.UseExceptionHandler("/Error");`, for web API exception I want to return Problem Detail `app.UseProblemDetails()`.

Here are snippets of my ConfigureServices
``` 
            services.AddProblemDetails(options => 
            {
                options.Rethrow((context, exception) =>
                {
                    return !context.Request.Path.StartsWithSegments(new PathString("/api"));
                });
            });         
```
and Configure
``` 
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseProblemDetails();
```

So, as you see I try to rethrow any exception which happens not within API request in order ExceptionHandlerMiddleware has a chance to handle it and show an error page. Usually, error handlers are not triggered if the response has already been written, the same in my case, ExeceptionHandlerMiddleware is never executed as the response has already been written by ProblemDetailsMiddleware.

With the help of options.IsProblem we can easily avoid having Problem Detail written to the response. Is there any way to avoid the response being written on exception?

Thanks!

**Comment by khellang** [comment]
Hi @vovapabyr! 👋🏻 

> With the help of `options.IsProblem` we can easily avoid having Problem Detail written to the response. Is there any way to avoid the response being written on exception?

No, that's basically what you have to control whether the middleware should treat it as a problem or not.

The middleware was written to always return uniform standardized problem details responses (on exception or HTTP status code) in JSON or XML. This is why it will write to the response, even if it's mapped to re-throw exceptions. Re-throwing was added to be able to do *additional* handling of exceptions upstream, like logging and APM.

Because of this, it might not be a good fit for an application also handles views, but I think you should be able to make it work with the existing knobs 😄

**Comment by vovapabyr** [comment]
Splitting request pipeline into two separate branches with IApplicationBuilder.Map solved my issue. Thanks!
