### ISSUE TITLE
FeatureRequest: Get the Object value into the detail property of the ProblemDetail

### ISSUE THREAD

**Issue by saegen** [khellang/Middleware#118]
I might be off the charts here since I'm new to this but testing through Postman gave me this:

return NotFound(); -> great!
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-ed9b48e7504dfc41a5227c7f88caacf6-03846fd5453f3b42-00"
}

return NotFound($"No Events for site with id was found"); -> No Events for site with id was found.
Not so great..

I would like this instead:
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    **"detail": "No Events for site with id was found"**      
    "traceId": "00-ed9b48e7504dfc41a5227c7f88caacf6-03846fd5453f3b42-00"
}

Perhaps there is another way to do this but from what I've seen it involves a lot coding from my perspective.

Sincerly  Tomas

**Comment by khellang** [comment]
Hi @saegen! 👋

Yeah, the problem here is MVC, which is at a higher level than this middleware. By the time the response reaches the middleware, MVC has already written to the body stream, which will flush the headers and start the response. At that point, it's too late to do anything.

Both of these responses are actually from MVC. If you want the middleware to handle client errors, you need to set `SuppressMapClientErrors`. See https://stackoverflow.com/q/61074642.

But even after suppression, MVC will write the response to the stream (in the latter case). There are a few ways to work around it, but they're not as pretty:

https://github.com/khellang/Middleware/blob/9ec5ff9fde03e1ff3e1744b91b8428817d704f4b/samples/ProblemDetails.Sample/Program.cs#L121-L148

**Comment by saegen** [comment]
Thank you most kindly for taking the time to reply Kristian! Awsome work, wish I could boast 1, 6 m 😄

Keep it up!

Best regards Tomas Hesse

Hämta Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by khellang** [comment]
Closing this as I'm not sure there's much I can do about this feature request 😅

**Comment by khellang** [comment]
Hi @saegen! 👋🏻 

I just pushed a new version, v5.2.0, to NuGet. It contains a new feature with some built-in conventions for MVC, which will get you the results you wanted.

You configure it like this:

```csharp
services.AddProblemDetails()
    .AddControllers()
        // Adds MVC conventions to work better with the ProblemDetails middleware.
        .AddProblemDetailsConventions()
```

Then in your controller, you can do this:

```csharp
[HttpGet("detail")]
public ActionResult<string> Detail()
{
    return BadRequest("This will end up in the 'detail' field.");
}
```

Which will give you the following output:

```json
{
  "type": "https://httpstatuses.com/400",
  "title": "Bad Request",
  "status": 400,
  "detail": "This will end up in the 'detail' field.",
  "traceId": "|605c9a15-41c50b8f52d8c412."
}
```

**Comment by khellang** [comment]
It will also take care of setting `SuppressMapClientErrors` for you, so you can remove any code related to that if you have it in your setup 😄

**Comment by saegen** [comment]
Excellent @khellang  I'll be sure to check it out!
