### ISSUE TITLE
[Question] UseForwardedHeaders order

### ISSUE THREAD

**Issue by Jimmys20** [khellang/Middleware#135]
Hi I have a question (might be stupid). I want to use Forwarded Headers. Microsoft says it can be called after diagnostics but must be called before UseHsts and other middleware. I use ProblemDetails middleware instead of UseDeveloperExceptionPage or UserExceptionHandler. Does it matter if app.UseForwardHeaders() is called before or after app.UseProblemDetails();

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#forwarded-headers-middleware-order

**Comment by khellang** [comment]
Hello @Jimmys20! 👋🏻

The middleware should ideally be placed as early in the pipeline as possible, in order to pick up potential exceptions downstream. The middleware itself doesn't really care about the request, which ForwardHeaders modifies, so it doesn't matter whether it's added before or after 😃

**Comment by Jimmys20** [comment]
Yes, adding ForwardHeaders at the very top and ProblemDetails right after makes sense. Thanks a lot!
