### ISSUE TITLE
Question: what is best practice when using this middle ware with other validation libraries?

### ISSUE THREAD

**Issue by RyanClementsHax** [khellang/Middleware#140]
Excellent library! You have saved me so much work and made my code so much cleaner!

I'm trying to use this with other validation libraries like FluentValidation. After doing some research and digging through old issues/discussions, it seems that you designed this library in mind for use with those libraries (great work). I'm still wondering what best practice is for mapping non-aspnet exceptions (like `FluentValidation.ValidationException`) to certain responses this middleware returns. It seems that I should use the following to map exceptions
```cs
options.Map<FluentValidation.ValidationException>(ex => ex.ToProblemDetails())
```
where the `ToProblemDetails` extension method could be defined as the following
```cs
public static class ProblemDetailsExtensions
{
    public static ValidationProblemDetails ToProblemDetails(this ValidationException ex)
        => new ValidationProblemDetails(
            ex.Errors
                .GroupBy(x => x.PropertyName)
                .ToDictionary(
                    x => x.Key,
                    x => x.Select(x => x.ErrorMessage).ToArray()
                )
        )
        {
            Status = StatusCodes.Status422UnprocessableEntity
        };
}
```
where `ValidationProblemDetails` is from aspnet (`Microsoft.AspNetCore.Mvc.ValidationProblemDetails`).

Doing it this way, I have to manually set the status code to the status code I want which, even though this is a `Microsoft.AspNetCore.Mvc.ValidationProblemDetails`, isn't treated like other `Microsoft.AspNetCore.Mvc.ValidationProblemDetails` created organically from invalid controller model states. For example, the middleware will automatically set the status value for the "organic" ones to whatever `ValidationProblemStatusCode` is set to in the options unless otherwise overridden, but not for the "artificial" ones.

I am able to get around this by creating my own `ValidationProblemDetails` class that extends from `Hellang.Middleware.ProblemDetails.StatusCodeProblemDetails` that effectively does the same thing, but now isn't the same type as all of the other problem details. This work around doesn't create a big problem, just has more of a chance to diverge from the other problem details implementation.

I see that the docs for `public void Map<TException>(Func<TException, Microsoft.AspNetCore.Mvc.ProblemDetails?> mapping) where TException : Exception;` say to return a `Hellang.Middleware.ProblemDetails` from the mapping function passed in, but I can't seem to find that class anywhere in the library.

This leads me to my question. What is the recommended way of proceeding and am I misusing/misunderstanding the library?

Thanks for your time and effort to this library.

**Comment by khellang** [comment]
Hi @RyanClementsHax! 👋🏻 

I'm glad you found the middleware helpful! 😄 

> For example, the middleware will automatically set the status value for the "organic" ones to whatever ValidationProblemStatusCode is set to in the options unless otherwise overridden, but not for the "artificial" ones.

By "organic ones", you mean validation results produced directly from MVC? I'm assuming you've called `AddProblemDetailsConventions`?

Those are produced by `ProblemDetailsFactory`, but unfortunately, it doesn't have an overload for passing in `IDictionary<string, string[]>` (to match the `ValidationProblemDetails` constructor), so it's a bit hard to use with FluentValidation.

I've pushed a new version to NuGet (v6.1.0) with a few new overloads to construct a `ValidationProblemDetails` instance using the factory, which will fill in the defaults configured in options. You can now use the factory to map the exception by doing something like this:

https://github.com/khellang/Middleware/blob/42597d3a43c1bbc1beeff4ab272432df03f0be08/samples/ProblemDetails.Sample/ProblemDetailsOptionsExtensions.cs#L7-L22

> I see that the docs for `public void Map<TException>(Func<TException, Microsoft.AspNetCore.Mvc.ProblemDetails?> mapping) where TException : Exception;` say to return a `Hellang.Middleware.ProblemDetails` from the mapping function passed in, but I can't seem to find that class anywhere in the library.

Ouch. That's actually a bug. The XML docs should point to `Microsoft.AspNetCore.Mvc.ProblemDetails`. It's been fixed in the new version 😅 

Let me know how it works out for you 😃

**Comment by RyanClementsHax** [comment]
> By "organic ones", you mean validation results produced directly from MVC? I'm assuming you've called `AddProblemDetailsConventions`?

Yeah that's what I did.

> Let me know how it works out for you 😃
Yup! I just integrated the new version and it works great! Thanks for the help. I appreciate the work!
