### ISSUE TITLE
Can we update the middleware to use a factory when setting the default values of a problem details?

### ISSUE THREAD

**Issue by stambunan** [khellang/Middleware#160]
Hi 👋 

I was wondering if we can update the middleware to accept a factory when setting the default values of a problem details? 

https://github.com/khellang/Middleware/blob/70ac2fb251baabc750c5a7e40e619cfc59c12e1f/src/ProblemDetails/ProblemDetailsFactory.cs#L108

My current use case is that we have a default factory that we would like to use when creating the problem details. We would like to customize the type, instance, and title easily. I think accepting a `IProblemDetailsFactory` or something of the likes might be useful in this scenario. The middleware can by default register a `DefaultProblemDetailsFactory` and if implementors decide to override this registration, they can.

**Comment by Phlank** [comment]
I think instead of adding a new interface, it might be better to add an option to accept some implementation of `Microsoft.AspNetCore.Mvc.Infrastructure.ProblemDetailsFactory`, since that is the type already being inherited by the ProblemDetailsFactory in the middleware.

The only issue with this is that there is currently a hard dependency on Middleware's ProblemDetailsFactory, and this inherently makes sense when it's injected into the service collection and used throughout this package; a full project may have many implementations of the MVC ProblemDetailsFactory added to the service collection.

Middleware's ProblemDetailsFactory is not sealed though, so it may just be a matter of inheriting _it_ in your own class rather than MVC's, and providing that type as an option. This feels kinda gross, but it would provide the configuration nonetheless.

Out of curiosity though - what needs do you have that the built-in options wouldn't actually solve? There are several options in this project, though the documentation for them is lacking from what I can tell.

**Comment by khellang** [comment]
Yeah, there shouldn't be a need for an additional extensibility point here. We've piggybacked on MVC's existing `ProblemDetailsFactory`, which is registered conditionally in the container:

https://github.com/khellang/Middleware/blob/eb7f59cb5aaff0727466622af6230db12703a32f/src/ProblemDetails/ProblemDetailsExtensions.cs#L34

This means that if you register your own implementation before calling `AddProblemDetails`, the middleware will happily use your implementation instead 😊

The documentation for the options is best viewed either from source or just in your IDE 😅

**Comment by stambunan** [comment]
That's a good point. I didn't think of inheriting it and customizing the `ProblemDetailsFactory`. I had tunnel vision and was thinking of figuring out a way to customize the middleware using Options that I didn't think of inheriting the class. Thanks!
