### ISSUE TITLE
Null "instance" property included in serialized StatusCodeProblemDetails

### ISSUE THREAD

**Issue by kjkrum** [khellang/Middleware#176]
It seems that a different JSON serializer is used when an exception is mapped to a `StatusCodeProblemDetails`. When I do this:

```C#
options.Map<BusinessException>((c, e) => new StatusCodeProblemDetails(StatusCodes.Status422UnprocessableEntity)
	{
		Detail = e.Message
	});
```

...the serialized `ProblemDetails` includes `"instance": null`. Other `ProblemDetails` responses omit null properties.

**Comment by khellang** [comment]
Hello @kjkrum! 👋

The middleware uses the JSON serializer used by MVC, so it should use the same options.

The issue might be because MVC internally wraps `ProblemDetails` in a serializer-specific instances which has some attributes related to serialization. What if you do `StatusCodeProblemDetails.Create` instead?

**Comment by kjkrum** [comment]
With `StatusCodeProblemDetails.Create`, null properties are not serialized. Thank you!
