### ISSUE TITLE
Version 6.5.0 wrong serialization of text/plain string values

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [khellang/Middleware#180]
Hello. Something changed between versions 6.4.4 and 6.5.0, and text/plain string values are now serialized including double quotes, whereas before it was a raw string value. This is observed with Postman calling my api. I'll see if I can create a simple repro for you, but wanted to get this logged asap.

<=6.4.4
`hello world`

=6.5.0
`"hello world"`

**Comment by ErikPilsits-RJW** [comment]
Minimal repro, project template is .NET Core Web Api on .net6.

Program.cs
```csharp
using Hellang.Middleware.ProblemDetails;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddProblemDetails(o =>
{
    o.IncludeExceptionDetails = (_, _) => builder.Environment.IsDevelopment() || builder.Environment.IsStaging();
    o.ShouldLogUnhandledException = (_, _, _) => false;
    o.SourceCodeLineCount = 2;
});

builder.Services.AddControllers();
var app = builder.Build();
app.UseProblemDetails();
app.MapControllers();
app.Run();
```

StringController.cs
```csharp
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers;

[ApiController]
[Route("[controller]")]
public class StringController : ControllerBase
{
    [HttpGet]
    public ActionResult<string> GetStringValue() => Ok("hello world");
}
```

<=6.4.4
![image](https://user-images.githubusercontent.com/68246095/183524279-6a09857e-26b7-467e-a091-4e0cc2c07fa7.png)

=6.5.0
![image](https://user-images.githubusercontent.com/68246095/183524312-65905596-b9b6-4aaf-8c78-fe6742064340.png)

**Comment by khellang** [comment]
Thanks for the bug report. I was a bit worried that could happen when adding the minimal API support.

What if you swap the order of the `AddControllers` and `AddProblemDetails` calls?

**Comment by ErikPilsits-RJW** [comment]
Actually yes, calling `AddControllers` first does fix the issue. Is this a requirement, or just a test?

**Comment by khellang** [comment]
> Is this a requirement, or just a test? Any other side effects to this change?

With achanged introduced to support Minimal APIs (without MVC), it became a requirement, which I didn't account for. I've pushed v6.5.1, which should hopefully address this issue.


## Some details

Since the beginning, this middleware has relied on an MVC service to serialize `ProblemDetails` responses (piggy-backing on MVC goodies like content negotiation etc.), but with Minimal APIs, you often don't have this service registered, which gives you an exception at runtime.

What I did was implement a lightweight version of this service using the Minimal APIs primitives (basically hard-coding everything as JSON), and did a `TryAdd` in `AddProblemDetails`. This will only add the service if it hasn't already been added (by MVC). See https://github.com/khellang/Middleware/commit/0b8552bbc88fccd0b2c699766e55bab058ed3cdd.

This introduced an ordering problem between `AddControllers` (which also uses `TryAdd`) and `AddProblemDetails`:
 - If you called `AddProblemDetails` first, you'd get the Minimal API-based version for everything (even MVC controllers)
 - If you called `AddControllers` first, you'd still get the existing behavior.

That's why it worked when you switched the order 😅

**Comment by khellang** [comment]
@ErikPilsits-RJW Are you able to verify the fix? 👼🏻

**Comment by ErikPilsits-RJW** [comment]
Yes I can, serialization looks normal after updating to 6.5.1, even with the previous `Add...` ordering. Thank you!
