### ISSUE TITLE
ProblemDetails middleware ignore errors from ActionFilterAttribute

### ISSUE THREAD

**Issue by lurumad** [khellang/Middleware#2]
Hi,

I usually try to manage model validation in an ActionFilterAttribute:

```csharp
public class ValidateModelStateFilter : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        if (context.ModelState.IsValid)
        {
            return;
        }

        var validation = new ValidationProblemDetails(context.ModelState);

        context.Result = new BadRequestObjectResult(validation);
    }
}
```

But ProblemDetails middleware ignore errors from this ActionFilterAttribute:

![error](https://user-images.githubusercontent.com/1729519/42946552-715fdbf4-8b6b-11e8-8c59-8204d0c6f22d.png)

I understand the first two conditionals in the method, but not the logic that decides the last:

```chsarp
if (context.Response.ContentLength.HasValue)
{
    return false;
}

if (string.IsNullOrEmpty(context.Response.ContentType))
{
    return true;
}
```
Regards!

**Comment by khellang** [comment]
Hi!

The assumption is that if `Content-Length` and `Content-Type` has been set, the response body has already been written by somone else. They're kinda redundant wince we also check `HasStarted`, but it follows the same rules as the exception handler middleware.

Someone else, in this case, is MVC's object result executor. It has already set the content type and written to the body by the time the problem details middleware is reached on the way out. This means it's too late for the middleware to write anything.

In this case it shouldn't matter whether the middleware or MVC's filter writes the response, since it's a `ValidationProblemDetails` instance. The JSON representation should be the same.

If you really need the MW to handle the response, you can throw a `ProblemDetailsException` and it should be handled automatically.

**Comment by lurumad** [comment]
Thanks @khellang

**Comment by khellang** [comment]
Nice. Glad you got it working! Incidentally, I just sent a PR to MVC to copy over the result status code to the problem details object, so from 2.2, you don't have to set it explicitly; https://github.com/aspnet/Mvc/pull/8118
