### ISSUE TITLE
Content-Type for BadRequest with ProblemDetails-object

### ISSUE THREAD

**Issue by nengberg** [khellang/Middleware#5]
Hi and thanks for your middlware for ProblemDetails! 👍 

This is more a question and not an issue (?):

When you return BadRequest with an object that is or derives from ProblemDetails the Content-Type will be application/json.

```
var problem = new OutOfCreditProblemDetails
{
     ...
};

return BadRequest(problem);
```

But when you return BadRequest without any object the Content-Type will be application/problem+json.

```
return BadRequest();
```

Is that by design?

Regards
Niklas

**Comment by khellang** [comment]
> Is that by design?

Not really. In the former case, it's actually MVC writing the body. The middleware is never involved. While the latter is just setting the status code and the middleware takes care of writing the body, which is why it has the correct content type.

Unfortunately, there's not much I can do about this in this repo, but I can take a stab at sending a PR to MVC to detect `ProblemDetails` and set the correct content type during result execution later.

A workaround is to specify the content type directly when returning the result from the action.

**Comment by nengberg** [comment]
That would be great! Thanks for the quick response!

**Comment by khellang** [comment]
I've filed https://github.com/aspnet/Mvc/issues/8467. I think that's the best place to track this.

If you need a workaround, you should explicitly add the content types:

https://github.com/khellang/Middleware/blob/4ccada48c2e141ef6b497d507c987b450d7511c0/src/ProblemDetails/ProblemDetailsMiddleware.cs#L157-L164

**Comment by khellang** [comment]
Looks like this will be fixed for ASP.NET Core 2.2 Preview 3; https://github.com/aspnet/Mvc/pull/8512
