### ISSUE TITLE
Get rid of null or empty properties

### ISSUE THREAD

**Issue by shuegelm** [khellang/Middleware#98]
Hey.

Short question because of missing documentation:
How to get rid of empty or not wanted properties (instance, extensions) inside the response? Do I need to set the right options in my JsonSerzializer or is there another way?

`{
    "type": "duplicate-key",

    "title": "An internal server error occured",

    "status": 500,

    "detail": "An identifier already exists. Please check your passed inputs.",

    "instance": null,

    "extensions": {}

}`

**Comment by khellang** [comment]
Yup, you need to configure the JSON serializer to ignore null values, like this:

https://github.com/khellang/Middleware/blob/413abc3de5e56d8beca401e7d7ff69e40a87bf61/samples/ProblemDetails.Sample/Program.cs#L43

Newtonsoft.Json has a similar setting. Also, extensions shouldn't really be included like that as it's a special property using `JsonExtensionData`.

What serializer are you using?

**Comment by shuegelm** [comment]
Hey @khellang,

thanks for the fast answer. I am using Microsoft.AspNetCore.Mvc.NewtonsoftJson, currently using .NET CORE 3.1.2

Need to find this option your mentioning.

**Comment by khellang** [comment]
For Newtonsoft, it's called `NullValueHandling`:

https://github.com/khellang/Middleware/blob/a8a477c41e26aee93a4e12dd9f963ae0d84aa499/samples/ProblemDetails.Sample/Program.cs#L39

**Comment by shuegelm** [comment]
Getting this problem:

![image](https://user-images.githubusercontent.com/12783126/78667575-81415400-78d9-11ea-9431-8b11d96c9c6e.png)

**Comment by khellang** [comment]
Right, if you're using ASP.NET Core 3.x, they've pulled out Newtonsoft.Json and replaced the method with a different one. I think it should be `AddNewtonsoftJson` now 🤔

**Comment by shuegelm** [comment]
```csharp
            services
                .AddMvc()
                .AddNewtonsoftJson(options =>
                {
                    options.UseCamelCasing(processDictionaryKeys: true);
                }).AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.IgnoreNullValues = true;
                }
            );
```

Not working :(

**Comment by khellang** [comment]
But you're not setting `NullValueHandling`? `AddJsonOptions` is configuring the System.Text.Json serializer.

**Comment by shuegelm** [comment]
Sorry was a bit on auto pilot in my head. I am lacking of options within and after AddNewtonsoftJson.

**Comment by shuegelm** [comment]
Got it, help from a friend.

```csharp
            services
                .AddControllers()
                .AddNewtonsoftJson(options =>
                {
                    options.UseCamelCasing(processDictionaryKeys: true);
                    options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                });
```

**Comment by khellang** [comment]
It's still too bad that the `extensions` field shows up in the serialized output when using Newtonsoft.Json, but that's due to https://github.com/khellang/Middleware/issues/74. Basically, MVC uses the `JsonExtensionData` attribute from System.Text.Json, which Newtonsoft.Json doesn't know about. In order to "fix" this, they register converters for the built-in `ProblemDetails` and `ValidationProblemDetails` types:

https://github.com/dotnet/aspnetcore/blob/7946b91a65ce0ff717bdcf528f6342edc5bfd92d/src/Mvc/Mvc.NewtonsoftJson/src/JsonSerializerSettingsProvider.cs#L47-L52

These basically wrap `ProblemDetails` and `ValidationProblemDetails` instances in special annotated types:

https://github.com/dotnet/aspnetcore/blob/7946b91a65ce0ff717bdcf528f6342edc5bfd92d/src/Mvc/Mvc.NewtonsoftJson/src/AnnotatedProblemDetails.cs#L46-L47

Which has the Newtonsoft.Json attributes on the properties instead. This is a horrible hack, which results in all sub-types of `ProblemDetails` to get this weird behavior where the `extensions` field is included instead of unwrapping the properties instead.

**Comment by khellang** [comment]
I just pushed a new version, v5.0, to NuGet, which no longer creates custom sub-types of ProblemDetails internally. This should hopefully also get rid of the issue where `extensions` is being included when Newtonsoft.Json is being used.
